inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
Naming/FileName:
  Exclude:
    - 'valkyrie-sequel.gemspec'
    - 'Gemfile'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'valkyrie-sequel.gemspec'
Metrics/ClassLength:
  Exclude:
    - 'lib/valkyrie/sequel/query_service.rb'
Metrics/ParameterLists:
  Exclude:
    - 'lib/valkyrie/sequel/metadata_adapter.rb'
RSpec/ExampleLength:
  Exclude:
    - 'spec/valkyrie/sequel/persister_spec.rb'
Rails/RakeEnvironment:
  Enabled: false
